#!/bin/bash

if [ $# -lt 2 ]
then
  echo "$0 package-name ros-distro [bloom-release options (e.g. --edit)]"
  exit 0
fi

if [ ! -f /home/${USER}/.config/bloom ]
then
  echo "{}" >> /home/${USER}/.config/bloom
fi

docker run --rm -it -v "/home/${USER}/.config/bloom:/root/.config/bloom:rw" -v "/home/${USER}/.gitconfig:/root/.gitconfig:ro" -v "/home/${USER}/.ssh/known_hosts:/root/.ssh/known_hosts:ro" -v $SSH_AUTH_SOCK:/ssh-agent --env SSH_AUTH_SOCK=/ssh-agent ros-bloom bloom-release $1 --track $2 --ros-distro $2 ${@:3}
